"""
Extract the USDA FoodData Central entries used by FOODLEK's seed ingredients.

Input: the per-country SQLite build published by the open-source project
CodeJetNet/food-data (https://github.com/CodeJetNet/food-data), which embeds
USDA FoodData Central (SR Legacy + Foundation, public domain) alongside Open
Food Facts data (ODbL). Only USDA rows are read here.

Usage:
    python3 scripts/data/extract_usda_subset.py path/to/foods-FR.db

Output: data/reference/usda-subset.json (committed, reviewed in diffs).

Why USDA and not Ciqual for the seed: Ciqual (ANSES, Licence Ouverte) is the
preferred reference for France and has a dedicated importer
(scripts/data/import-ciqual.ts). The seed must however be reproducible in
environments where the Ciqual files cannot be downloaded; USDA values are
public domain, versioned and identified by FDC id, so they are a legitimate,
traceable fallback. Every value keeps its source in the database.
"""
import json
import sqlite3
import sys
from pathlib import Path

FDC_IDS = [
    "171077", "171790", "171287", "175167", "171955", "173709", "174515", "173800",
    "174284", "172475", "170894", "173420", "170847", "325036", "168877", "168878",
    "169736", "169737", "170026", "168482", "169699", "175037", "172675", "168874",
    "169291", "170393", "170000", "1104647", "170108", "170457", "170051", "169287",
    "747447", "169962", "169251", "2346406", "169249", "169246", "2685573", "170016",
    "2685577", "167746", "171413", "173410", "171256", "170173", "172205", "174278",
    "170924", "170923", "171329", "173468", "170931", "169640", "170459", "326698",
    "170416", "169214", "171705", "174285", "169231", "170005", "172232", "169997",
    "171242",
    # Catalogue élargi (septembre 2026) : desserts, petits-déjeuners, nouveaux plats.
    "173627", "173430", "170858", "332397", "168277", "175179", "175139", "169433", "168249", "172420",
    "172421", "175203", "2259793", "171248", "173435", "170859", "173904", "168936",
    "170688", "170287", "169742", "168914", "335240", "174924", "168931", "168932",
    "168867", "172790", "168462", "2685570", "169975", "169146", "169276", "169094",
    "171688", "173944", "746773", "169097", "327046", "2346409", "2346411", "168209",
    "169910", "168155", "168165", "746784", "170273", "168774", "171320", "170567",
    "170187", "172470", "169641", "170554", "170170", "170938", "171328", "169994",
    "173475", "171326",
]

NUTRIENTS = {
    "energyKcal": "n1008",
    "proteinG": "n1003",
    "fatG": "n1004",
    "carbsG": "n1005",
    "fiberG": "n1079",
    "sugarsG": "n2000",
    "saturatedFatG": "n1258",
    "sodiumMg": "n1093",
}

SOURCE_LABELS = {
    "usda_sr": ("USDA_SR_LEGACY", "USDA FoodData Central – SR Legacy", "SR Legacy (2018-04)"),
    "usda_foundation": ("USDA_FOUNDATION", "USDA FoodData Central – Foundation Foods", "Foundation Foods"),
}


def main(db_path: str) -> None:
    db = sqlite3.connect(db_path)
    meta = dict(db.execute("select key, value from meta").fetchall())
    cols = ", ".join(NUTRIENTS.values())
    foods = {}
    for fdc in FDC_IDS:
        row = db.execute(
            f"select id, name, source, {cols} from foods where source_id = ? and source like 'usda%'",
            (fdc,),
        ).fetchone()
        if row is None:
            raise SystemExit(f"FDC id {fdc} not found in {db_path}")
        food_id, name, source = row[0], row[1], row[2]
        values = row[3:]
        kind, label, version = SOURCE_LABELS[source]
        portions = [
            {"description": d, "grams": g}
            for d, g in db.execute("select description, grams from portions where food_id = ?", (food_id,))
        ]
        foods[fdc] = {
            "fdcId": fdc,
            "name": name,
            "source": kind,
            "sourceLabel": label,
            "sourceVersion": version,
            "per100g": {
                key: (None if v is None else round(float(v), 4)) for key, v in zip(NUTRIENTS.keys(), values)
            },
            "portions": portions,
            "url": f"https://fdc.nal.usda.gov/food-details/{fdc}/nutrients",
        }
    out = {
        "_about": (
            "USDA FoodData Central values (public domain) for FOODLEK seed ingredients. "
            "Generated by scripts/data/extract_usda_subset.py; do not edit by hand."
        ),
        "extractedFrom": {
            "dataset": "CodeJetNet/food-data foods-FR.db",
            "builtAt": meta.get("builtAt"),
            "attribution": meta.get("attribution"),
        },
        "license": "USDA FoodData Central data are in the public domain (CC0 1.0).",
        "foods": foods,
    }
    target = Path(__file__).resolve().parents[2] / "data" / "reference" / "usda-subset.json"
    target.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(foods)} foods to {target}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
